universe = docker
docker_image = madgraph5-amc-nlo:mg5_amc3.3.1

executable = small_gen.sh
arguments = $(ClusterId)$(ProcId)
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

output = sm_x_01.$(ClusterId).$(ProcId).out
error = error/sm_x_01.$(ClusterId).$(ProcId).err
log = log/sm_x_01.$(ClusterId).$(ProcId).log

output_destination = root://eosuser.cern.ch//eos/user/j/jashley/tutorials_and_tests/condor_tutorial/output/

queue
